service: avatar-resizer

custom:
  source-bucket: "svls-avatars"
  resized-bucket: "svls-resized"

provider:
  name: aws
  runtime: java8
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "s3:GetObject"
    Resource: "arn:aws:s3:::${self:custom.source-bucket}/*"
  - Effect: "Allow"
    Action:
    - "s3:ListBucket"
    Resource: "arn:aws:s3:::${self:custom.resized-bucket}"
  - Effect: "Allow"
    Action:
    - "s3:DeleteObject"
    - "s3:PutObject"
    Resource: "arn:aws:s3:::${self:custom.resized-bucket}/*"
  environment:
    TARGET_BUCKET: ${self:custom.resized-bucket}

package:
  artifact: build/distributions/avatar-resizer.zip

functions:

  delete-avatar-handler:
    handler: me.aerben.handlers.DeleteAvatarHandler
    events:
    - s3:
        bucket: ${self:custom.source-bucket}
        event: s3:ObjectRemoved:*

  resize-avatar-handler:
    handler: me.aerben.handlers.ResizeAvatarHandler
    events:
    - s3:
        bucket: ${self:custom.source-bucket}
        event: s3:ObjectCreated:*

  configuration-handler:
    handler: me.aerben.handlers.ConfigurationHandler

resources:
  Resources:
    ResizedAvatarsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.resized-bucket}
